sudo: required
before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt541
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt54base qt54serialport qt54tools
    - source /opt/qt54/bin/qt54-env.sh
    - gem install fpm
script:
    - qmake -v
    - qmake
    - make
    - ldd bin/cutecom-ng
    - cp deploy/linux/* bin/
    - cp /opt/qt54/lib/libQt5{SerialPort,Widgets,Gui,Core}.so.5 bin/
    - ls -l bin/
    - fpm -s dir -t deb -n cutecom-ng -v 0.1 --prefix /opt/cutecom-ng bin/
    - dpkg --contents *.deb
